<div class="page-header">
    <h1>Crear Usuario</h1>
</div>
<div class="row">
    <div class="span3">
        <?php KumbiaPHP\View\View::partial('K2/Backend:menus/usuarios') ?>
    </div>
    <div class="span8 span-derecho" >
        <div id="res-form-ajax">
            <?php KumbiaPHP\View\View::content(true) ?>
        </div>
        <?php echo $form->open(array(
            'class' => 'form-horizontal js-remote',
            'data-div' => 'res-form-ajax'
        )) ?>
        <div class="control-group">
            <label class="control-label" for="usuario_login"><?php echo $form['login']['label'] ?>* :</label>
            <div class="controls">
                <?php echo $form['login'] ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="usuario_clave"><?php echo $form['clave']['label'] ?>* :</label>
            <div class="controls">
                <?php echo $form['clave'] ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="usuario_clave2"><?php echo $form['clave2']['label'] ?>* :</label>
            <div class="controls">
                <?php echo $form['clave2'] ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="usuario_nombres"><?php echo $form['nombres']['label'] ?>* :</label>
            <div class="controls">
                <?php echo $form['nombres'] ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="usuario_email"><?php echo $form['email']['label'] ?>* :</label>
            <div class="controls">
                <?php echo $form['email'] ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="usuario_email"><?php echo $form['roles']['label'] ?>* :</label>
            <div class="controls">
                <?php echo $form['roles']->render('<br/>') ?>
            </div>
        </div>
        <div class="form-actions">
            <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
        </div>
        <?php echo $form->close() ?>
    </div>
</div>