<div class="page-header">
    <h1>
        Edición del Usuario
        <small><?php eh(strtoupper($usuario->login)) ?></small>
    </h1>
</div>
<div class="row">
    <div class="span3">
        <?php KumbiaPHP\View\View::partial('K2/Backend:menus/usuarios') ?>
    </div>
    <div class="span8 span-derecho">
       <div id="res-form-ajax">
            <?php KumbiaPHP\View\View::content(true) ?>
            <?php KumbiaPHP\View\View::partial('K2/Backend:form_errors', FALSE, array('form' => $form)) ?>
        </div>
        <?php echo $form->open(array('class' => 'form-horizontal')) ?>
        <div class="control-group">
            <label class="control-label" for="usuario_email"><?php echo $form['roles']['label'] ?>* :</label>
            <div class="controls">
                <?php echo $form['roles'] ?>
            </div>
        </div>
        <div class="form-actions">
            <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
        </div>
        <?php //echo Form::close() ?>
        <?php echo $form->close() ?>
    </div>
</div>