<div class="page-header">
    <h1>Usuarios del Sistema</h1>
</div>
<div id="mensajes_flash" >        
    <?php \K2\View\View::content(true) ?>
</div> 
<?php
\K2\View\View::partial('K2/Backend:barra_superior_listas', FALSE, array('texto' => 'Crear Usuario', 'opciones' => FALSE));
$dt = new \K2\Backend\Lib\DataTable($usuarios);
$dt->addHeaders('id', 'Login', 'Nombres', 'Correo Electronico', 'Estado', 'Editar');
$dt->addFields('id', 'login', 'nombres', 'email');
$dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png', 'admin/usuarios/activar|admin/usuarios/desactivar', '', 'activo');
$dt->imgLink('figuras/editar.png', 'admin/usuarios/editar');
echo $dt->render('class="table table-bordered table-striped"');
?>
