<div class="page-header">
    <h1>Configuraci&oacute;n de Perfil</h1>
</div>       
<?php KumbiaPHP\View\View::content(true) ?>
<ul class="nav nav-tabs">
    <li class="active"><a href="#datos-personales" data-toggle="tab">Datos Personales</a></li>
    <li><a href="#clave" data-toggle="tab">Contrase&ntilde;a</a></li>
</ul>
<div class="tab-content">
    <div id="datos-personales" class="tab-pane active">
        <?php KumbiaPHP\View\View::partial('K2\Backend:form_errors', FALSE, array('form' => $form1)) ?>
        <?php echo $form1->open(array(
            'class' => 'form-horizontal js-remote',
            'data-div' => 'res-datos-personales'
        )); ?>
        <fieldset>
            <legend>Configurar Datos Personales</legend>
            <br/>
            <div id="res-datos-personales"></div>
            <div class="control-group">                
                <label class="control-label" for="perfil_nombres"><?php echo $form1['nombres']['label'] ?></label>
                <div class="controls">
                    <?php echo $form1['nombres'] ?>
                </div>
            </div>
            <div class="control-group">                
                <label class="control-label" for="perfil_email"><?php echo $form1['email']['label'] ?></label>
                <div class="controls">
                    <?php echo $form1['email'] ?>
                </div>
            </div>
            <div class="form-actions">
                <?php echo Form::submit('Guardar Cambios', 'name="datos_personas" class="btn btn-primary"') ?>
            </div>
        </fieldset>
        <?php echo $form1->close(); ?>
    </div>
    <div id="clave" class="tab-pane">
        <?php KumbiaPHP\View\View::partial('K2\Backend:form_errors', FALSE, array('form' => $form2)) ?>
        <?php echo $form2->open(array(
            'class' => 'form-horizontal js-remote',
            'data-div' => 'res-clave'
        )) ?>
        <fieldset>
            <legend>Cambiar Contrase&ntilde;a</legend>
            <br/>
            <div id="res-clave"></div>
            <div class="control-group">
                <label class="control-label" for="cambioClave_clave_actual"><?php echo $form2['clave_actual']['label'] ?></label>
                <div class="controls">
                    <?php echo $form2['clave_actual'] ?>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="cambioClave_nueva_clave"><?php echo $form2['nueva_clave']['label'] ?></label>
                <div class="controls">
                    <?php echo $form2['nueva_clave'] ?>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="cambioClave_clave2"><?php echo $form2['clave2']['label'] ?></label>
                <div class="controls">
                    <?php echo $form2['clave2'] ?>
                </div>
            </div>
            <div class="form-actions">
                <?php echo Form::submit('Guardar Cambios', 'name="cambiar_clave" class="btn btn-primary"') ?>
            </div>
        </fieldset>
        <?php echo Form::close() ?>
    </div>
</div>