<?php

use K2\Backend\Model\Roles;

Roles::createQuery()
        ->limit(8)
        ->order('id DESC');
$res = Roles::findAll();

$actual = Form::getFieldValue('rol.id') //vriable con el id del registro que se edita 
?>

<ul class="nav nav-tabs nav-stacked visible-desktop">
    <?php foreach ($res as $e): ?>
        <li class="<?php if ($e->id == $actual) echo 'active'; ?>">
            <?php $content = h(strtoupper($e->rol)); ?>
            <?php echo Html::linkAction("editar/$e->id", $content); ?>
        </li>
    <?php endforeach; ?>
</ul>