<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset='<?php echo APP_CHARSET ?>' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?php echo KumbiaPHP\View\View::get('container')->getParameter('config.name')   ?></title>
        <?php
        Tag::css('style');
        Tag::css('bootstrap.min');
        Tag::css('backend/estilos');
        Tag::js('jquery/jquery.min', -100);
        Tag::js('jquery/jquery.kumbiaphp');
        Tag::js('bootstrap.min');
        Tag::js('global');
        echo Html::includeCss();
        ?>
    </head>
    <body>
        <?php \KumbiaPHP\View\View::partial('K2/Backend:backend/cabecera_admin') ?>
        <div class="container">
            <div id="contenido" class="content">
                <?php \KumbiaPHP\View\View::content(); ?>
            </div>
            <?php \KumbiaPHP\View\View::partial('K2/Backend:backend/pie') ?>
        </div>
        <?php echo Html::includeJs(); ?>
    </body>
</html>
