<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset='<?php echo APP_CHARSET ?>' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?php echo \KumbiaPHP\Kernel\Kernel::getParam('config.name') ?></title>
        <?php
        Tag::css('style');
        Tag::css('bootstrap.min');
        Tag::css('backend/estilos');
        Tag::js('jquery/jquery.min', -100);
        Tag::js('jquery/jquery.kumbiaphp');
        Tag::js('bootstrap.min');
        Tag::js('global');
        echo Html::includeCss();
        ?>
        <style>
            #form_logueo label.control-label{
                width: 75px !important;
            }
            #form_logueo .controls{
                margin-left: 90px !important;
            }
        </style>
    </head>
    <body>
        <?php //\KumbiaPHP\View\View::partial('K2/Backend:cabecera_app'); ?>
        <div class="container">
            <div id="contenido" class="content">
                <div id="form_logueo" class="modal" style="position:relative; top: auto; left: auto; margin: 0 auto; z-index: 1">
                    <div class="modal-header">
                        <h3>Iniciar Sesi&oacute;n</h3>                        
                    </div>
                    <div class="modal-body">
                        <?php \KumbiaPHP\View\View::content(true) ?>
                        <?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
                        <div class="control-group">
                            <label class="control-label" for="login">Usuario </label>
                            <div class="controls">
                                <?php echo Form::text('form_login.login') ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="clave">Contrase&ntilde;a </label>
                            <div class="controls">
                                <?php echo Form::pass('form_login.clave', 'autocomplete="off"') ?>
                            </div>
                        </div>
                        <?php if (\KumbiaPHP\Kernel\Kernel::getParam('k2.backend.recordar_sesion')): ?>
                            <div class="controls">
                                <label class="checkbox">
                                    <?php //echo Form::check('recordar', 1, NULL, MyAuth::cookiesActivas()) ?> No cerrar Sesión
                                </label>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="modal-footer">
                        <?php if (\KumbiaPHP\Kernel\Kernel::getParam('k2.backend.registro')): ?>
                            <?php echo Html::link('registro', 'Registrate') ?>
                        <?php endif; ?>
                        <?php echo Form::submit('Ingresar', 'class="btn btn-primary btn-large"') ?>
                    </div>
                    <?php echo Form::close() ?>
                </div>
            </div>
            <footer>
                <p>
                    <?php
                    echo 'Tiempo: ' . round((microtime(1) - START_TIME), 4) . ' seg.';
                    echo ', Memoria Usada: ' . number_format(memory_get_usage() / 1048576, 2) . ' MB';
                    ?>
                </p>
            </footer>
        </div>
        <?php echo Html::includeJs(); ?>
    </body>
</html>
