<div id='cabecera' class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar pull-right" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand">Modulo de Administracion</a>
            <div class="nav-collapse">
                <?php
                echo \K2\View\View::partial("K2/Backend:menu", false, array(
                    'items' => K2\Backend\Model\Menus::getItems(K2\Backend\Model\Menus::BACKEND)))
                ?>
                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="text-transform: capitalize;">
                            <?php eh(\K2\Kernel\App::get('security')->getToken('nombres')) ?>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><?php echo Html::link('logout', 'Salir') ?></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
