<?php

use K2\View\View;

/*
 * Partial que genera los mensajes flash en formato html
 */
?>
<div class="messages-flash">
    <?php foreach ((array) View::flash()->getAll() as $type => $messages): ?>
        <?php foreach ((array) $messages as $message): ?>
            <div class="alert alert-<?php echo $type ?>"><?php echo $message ?>
                <button type="button" class="close" data-dismiss="alert">×</button>
            </div>
        <?php endforeach; ?>
    <?php endforeach; ?>
</div>
