<?php

use K2\Backend\Model\Menus;
use K2\Kernel\App;
use K2\View\View;

isset($classes) || $classes = 'nav';

$security = App::get("security");
?>
<!--Inicia Menú-->
<?php if ($items): ?>
    <ul class="<?php echo $classes ?>"> 
        <?php foreach ($items as $item): ?>
            <?php //si tiene permisos para acceder al menú ?>
            <?php if ($security->hasPermissions($item->getUrl())): ?>
                <?php $hasSubItems = $item->hasSubItems() ?>
                <?php if ($hasSubItems) : ?>
                    <li class="dropdown">
                        <?php echo Html::link($item->getUrl(), h($item->getTitle()) . ' <b class="caret"></b>', 'class="dropdown-toggle" data-toggle="dropdown"') ?>
                        <?php
                        View::partial('K2/Backend:menu', false, array(
                            'items' => $item->getSubItems(),
                            'classes' => 'dropdown-menu',
                        ));
                        ?>
                    <?php else: ?>
                    <li class="">
                        <?php echo Html::link($item->getUrl(), h($item->getTitle())) ?>
                    <?php endif; ?>
                </li>
            <?php endif; ?>
        <?php endforeach ?>
    </ul>
<?php endif; ?>
<!-- Fin Menú-->