<div class="page-header">
    <h1>Roles (Perfiles) del Sistema</h1>
</div>
<?php \K2\View\View::content(true) ?>
<?php
echo Form::open('admin/roles/eliminar', 'post', 'class="form_lista"');
\K2\View\View::partial('K2/Backend:barra_superior_listas', FALSE, array('texto' => 'Crear Rol'));
$dt = new K2\Backend\Lib\DataTable($roles);
$dt->addHeaders(Form::check('seleccionar_todos', 'todos', NULL, FALSE));
$dt->addHeaders('id', 'Rol', 'plantilla a usar', 'Estado', 'Editar', 'Eliminar');
$dt->check('roles_id');
$dt->addFields('id', 'rol', 'plantilla');
$dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png',
        'admin/roles/activar|admin/roles/desactivar', '', 'activo');
$dt->imgLink('figuras/editar.png', 'admin/roles/editar');
$dt->imgLinkConfirm('figuras/eliminar.png', 'admin/roles/eliminar', '', '¿Realmente desea Eliminar Este Rol?');
echo $dt->render('class="table table-bordered table-striped"');
echo Form::close();
?>
