<div class="page-header">
    <h1>Recursos del Sistema
        <?php echo Html::linkAction('escaner', 'Escanear Recursos por Agregar', 'class="btn btn-primary pull-right hidden-phone"') ?>
    </h1>
</div>
<?php \KumbiaPHP\View\View::content(true) ?>
<?php
echo Form::open('admin/recursos/eliminar', 'post', 'class="form_lista"');
\KumbiaPHP\View\View::partial('K2/Backend:barra_superior_listas', FALSE, array('texto' => 'Crear Recurso'));
$dt = new K2\Backend\Lib\DataTable($recursos);
$dt->addHeaders(Form::check('seleccionar_todos', 'todos', NULL, FALSE));
$dt->addHeaders('id', 'ruta', 'Descripción', 'Estado');
$dt->addHeaders('Editar', 'Eliminar');
$dt->check('recursos_id');
$dt->addFields('id', 'recurso', 'descripcion');
$dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png', 'admin/recursos/activar|admin/recursos/desactivar', '', 'activo');
$dt->imgLink('figuras/editar.png', 'admin/recursos/editar');
$dt->imgLinkConfirm('figuras/eliminar.png', 'admin/recursos/eliminar', '', '¿Realmente desea Eliminar Este Recurso?');
echo $dt->render('class="table table-bordered table-striped"');
echo Form::close();
?>